{% set name = "staircase" %}
{% set version = "2.6.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 91804af04f1566463eeb336f9109ceae330d93d7361570d32f934cbbbb5aec6e

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python {{ python_min }}
    - poetry
  run:
    - matplotlib-base >3.0.0,<4
    - numpy >=1.16.0,<2
    - pandas >=1,<3
    - python >={{ python_min }},<4
    - typing-extensions >=4.4.0
    - pytz

test:
  requires:
    - python {{ python_min }}
  imports:
    - staircase

about:
  home: https://staircase.dev
  summary: A data analysis package based on modelling and manipulation of mathematical step functions. Strongly aligned with pandas.
  license: MIT
  license_file: LICENSE
  description: |
    A data analysis package based on modelling and manipulation of mathematical step functions. Strongly aligned with pandas.
  doc_url: https://staircase.dev
  doc_source_url: https://github.com/staircase-dev/staircase/blob/master/docs/index.rst
  dev_url: https://github.com/staircase-dev/staircase


extra:
  recipe-maintainers:
    - staircase-dev
    - venaturum
